version: "3"

services:
  ingress:
    image: nginx
    volumes:
      - ./nginxconf/:/etc/nginx/conf.d/
    ports:
      - 8080:8080
    depends_on:
      - backend
    network_mode: host
  backend:
    build: .
    volumes:
      - ./src/:/home/node/app/src
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      # for DB SERVICE
      - DATABASE_LINK=db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=chiangkhan
      - DATABASE_PORT=5432
    command: yarn start:dev
    depends_on:
      - db
  db:
    image: postgres:11.7
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres-context:/docker-entrypoint-initdb.d
